### Funciones

In [6]:
def nota_final(prueba1,prueba2,prueba3,prueba4):
    promedio_pruebas = round((prueba1+prueba2+prueba3+prueba4)/4,1)
    print(promedio_pruebas)
    if promedio_pruebas > 4:
        return print('Aprobado')
    else:
        return print('Desaprobado')
    

p1 = int(input('Nota 1:'))
p2 = int(input('Nota 2:'))
p3 = int(input('Nota 3:'))
p4 = int(input('Nota 4:'))

nota_final(p1,p2,p3,p4)

3.8
Desaprobado

### Parametros y argumentos

In [7]:
def saludo(nombre):
    print(f'Buenos dias {nombre}!')


saludo('Federico')

Buenos dias Federico!

In [8]:
def saludo():
    nombre = input('Cual es tu nombre?')
    print(f'Buenos dias {nombre}')

saludo()

Buenos dias Federico

In [9]:
def promedio_lista(lista):

    suma = 0
    for i in lista:
        suma += i
    
    promedio = round(suma/len(lista),1)

    return (promedio)


print(promedio_lista([4,5,6,7,3,5,3,6,3,5]))

4.7

### ARGUMENTOS Y VARIABLES

In [10]:
def potencia(base,exponente):

    return base ** exponente


print(potencia(3,6))

729

In [11]:
# Funciones para DataFrame

import pandas as pd

In [12]:
df = pd.read_excel('DataFrame.xlsx')

In [15]:
df = df.drop(columns='Unnamed: 0')

In [19]:
def square(x):
    return x * x

edades = df['Edad'].apply(square)
df['EdadSQR'] = edades

In [20]:
df

,ID,Rol,Sexo,Edad,Fecha,Hora,Comuna,Participantes,Victima,Acusado,Día de semana,EdadSQR
0,2019-0026,PEATON,MASCULINO,0,2019-03-28,7,8,PEATON-PASAJEROS,PEATON,PASAJEROS,Jueves,0
1,2021-0012,PEATON,MASCULINO,0,2021-01-29,20,8,PEATON-AUTO,PEATON,AUTO,Viernes,0
2,2016-0041,PASAJERO_ACOMPAÑANTE,MASCULINO,0,2016-03-29,11,7,MOTO-CARGAS,MOTO,CARGAS,Martes,0
3,2019-0095,CONDUCTOR,MASCULINO,0,2019-11-20,15,1,MOTO-CARGAS,MOTO,CARGAS,Miercoles,0
4,2019-0094,PASAJERO_ACOMPAÑANTE,FEMENINO,0,2019-11-18,14,15,MOTO-OTRO,MOTO,OTRO,Lunes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0071,PEATON,MASCULINO,88,2021-08-31,16,3,PEATON-MOTO,PEATON,MOTO,Martes,7744
713,2020-0055,PEATON,MASCULINO,91,2020-11-19,12,12,PEATON-CARGAS,PEATON,CARGAS,Jueves,8281
714,2020-0028,PEATON,MASCULINO,91,2020-05-19,10,15,PEATON-PASAJEROS,PEATON,PASAJEROS,Martes,8281
715,2019-0089,PEATON,FEMENINO,92,2019-10-23,15,4,PEATON-CARGAS,PEATON,CARGAS,Miercoles,8464
716,2017-0080,PEATON,FEMENINO,95,2017-06-22,10,9,PEATON-CARGAS,PEATON,CARGAS,Jueves,9025

In [26]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             717 non-null    object
 1   Rol            717 non-null    object
 2   Sexo           717 non-null    object
 3   Edad           717 non-null    int64
 4   Fecha          717 non-null    object
 5   Hora           717 non-null    int64
 6   Comuna         717 non-null    int64
 7   Participantes  717 non-null    object
 8   Victima        708 non-null    object
 9   Acusado        694 non-null    object
 10  Día de semana  717 non-null    object
 11  EdadSQR        717 non-null    int64
dtypes: int64(4), object(8)
memory usage: 67.3+ KB

In [27]:
df['Rol'] = df['Rol'].apply(str.lower)

In [28]:
df

,ID,Rol,Sexo,Edad,Fecha,Hora,Comuna,Participantes,Victima,Acusado,Día de semana,EdadSQR
0,2019-0026,peaton,MASCULINO,0,2019-03-28,7,8,PEATON-PASAJEROS,PEATON,PASAJEROS,Jueves,0
1,2021-0012,peaton,MASCULINO,0,2021-01-29,20,8,PEATON-AUTO,PEATON,AUTO,Viernes,0
2,2016-0041,pasajero_acompañante,MASCULINO,0,2016-03-29,11,7,MOTO-CARGAS,MOTO,CARGAS,Martes,0
3,2019-0095,conductor,MASCULINO,0,2019-11-20,15,1,MOTO-CARGAS,MOTO,CARGAS,Miercoles,0
4,2019-0094,pasajero_acompañante,FEMENINO,0,2019-11-18,14,15,MOTO-OTRO,MOTO,OTRO,Lunes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0071,peaton,MASCULINO,88,2021-08-31,16,3,PEATON-MOTO,PEATON,MOTO,Martes,7744
713,2020-0055,peaton,MASCULINO,91,2020-11-19,12,12,PEATON-CARGAS,PEATON,CARGAS,Jueves,8281
714,2020-0028,peaton,MASCULINO,91,2020-05-19,10,15,PEATON-PASAJEROS,PEATON,PASAJEROS,Martes,8281
715,2019-0089,peaton,FEMENINO,92,2019-10-23,15,4,PEATON-CARGAS,PEATON,CARGAS,Miercoles,8464
716,2017-0080,peaton,FEMENINO,95,2017-06-22,10,9,PEATON-CARGAS,PEATON,CARGAS,Jueves,9025